import { Project } from '@app-types';

export const PROJECTS: Project[] = [
  {
    id: 'hostel-bites',
    title: 'Hostel-Bites',
    date: '2025',
    description: 'Firebase-based meal ordering platform for hostel students.',
    tech: ['HTML', 'CSS', 'JavaScript', 'Firebase'],
    github: 'https://github.com/dikshadamahe/Hostel-Bites',
    live: 'https://hostel-bites-1.web.app',
  },
  {
    id: 'ielts',
    title: 'IELTS Precision & Progress',
    date: 'Sep 2025',
    description: 'Conversion-focused IELTS institute landing page with metric cards, testimonials, and enrollment form.',
    tech: ['React', 'TypeScript', 'Vite', 'Tailwind CSS', 'Framer Motion'],
    github: 'https://github.com/dikshadamahe/IELTS',
    live: 'https://ielts-nu.vercel.app',
  },
  {
    id: 'aegis-vault',
    title: 'Aegis Vault',
    date: 'Oct 2025',
    description: 'Secure password manager with client-side envelope encryption and searchable vault dashboard.',
    tech: ['Next.js', 'TypeScript', 'MongoDB', 'Prisma', 'NextAuth', 'libsodium'],
    github: 'https://github.com/dikshadamahe/Aegis-Vault',
    live: 'https://aegis-vault.vercel.app',
  },
  {
    id: 'vyomgarud',
    title: 'VyomGarud',
    date: 'Nov 2025',
    description: 'Cinematic counter-UAV defense marketing site with hero video, animated metrics, and product sections.',
    tech: ['Next.js', 'React', 'Tailwind CSS', 'Framer Motion'],
    github: 'https://github.com/dikshadamahe/Vyom-Garud',
    live: 'https://vyom-garud-seven.vercel.app',
  },
  {
    id: 'fossee',
    title: 'FOSSEE Chemical Equipment Visualizer',
    date: 'Feb 2026',
    description: 'Hybrid web + desktop analytics for chemical equipment. Django REST backend, React web, PyQt5 desktop, shared API.',
    tech: ['Django', 'DRF', 'React', 'PyQt5', 'Chart.js', 'Pandas'],
    github: 'https://github.com/dikshadamahe/fossee-project',
    live: 'https://fossee-project-eta.vercel.app',
  },
  {
    id: 'nafld',
    title: 'NAFLD Risk Stratification Pipeline',
    date: 'Feb 2026',
    description: 'Research ML pipeline benchmarking 24 classifiers on NHANES data. Best model: AdaBoost at 0.9679 ROC-AUC.',
    tech: ['Python', 'scikit-learn', 'XGBoost', 'SHAP', 'Matplotlib'],
    github: 'https://github.com/dikshadamahe/NAFLD-Model',
    live: null,
  },
  {
    id: 'note-assistant',
    title: 'Note Assistant Chatbot',
    date: 'Mar 2026',
    description: 'BERT-based semantic search chatbot for note retrieval.',
    tech: ['Python', 'BERT', 'NLP'],
    github: 'https://github.com/dikshadamahe/Note-Assistant-chatbot-',
    live: null,
  },
  {
    id: 'veil',
    title: 'Veil Android',
    date: '2026',
    description: 'Flutter-based streaming client application.',
    tech: ['Flutter', 'Dart', 'TypeScript'],
    github: 'https://github.com/dikshadamahe/veil-android',
    live: null,
  },
  {
    id: 'recovai',
    title: 'RecovAI',
    date: 'May 2026',
    description: 'AI decision-support for copper flotation at HCL. Predicts recovery (R² 0.972), optimizes reagent dosing, SHAP explanations. Trained on 1,778 digitized shift logs.',
    tech: ['Python', 'XGBoost', 'SHAP', 'FastAPI', 'SciPy', 'SQLite'],
    github: 'https://github.com/dikshadamahe/RecovAI',
    live: 'https://recovai-xys2.onrender.com',
  },
];
